/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Yang Tao",
  "description": "",
  "base": "/bigking/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImage": "/back.jpg",
        "bgImageStyle": {
          "height": "750px"
        },
        "heroText": "Yang Tao",
        "tagline": "前端就是不断重复造轮子的过程",
        "heroTextStyle": {
          "font-size": "26px",
          "color": "#FFF"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-52eef96c",
      "path": "/"
    },
    {
      "title": "svg",
      "frontmatter": {
        "title": "svg",
        "date": "2021-12-13T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "svg"
        ]
      },
      "regularPath": "/components/Dashboard.html",
      "relativePath": "components/Dashboard.md",
      "key": "v-4014f6f4",
      "path": "/components/Dashboard.html"
    },
    {
      "title": "一些奇怪的按钮",
      "frontmatter": {
        "title": "一些奇怪的按钮",
        "date": "2021-11-07T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "btn"
        ]
      },
      "regularPath": "/components/btn.html",
      "relativePath": "components/btn.md",
      "key": "v-98e0ed38",
      "path": "/components/btn.html"
    },
    {
      "title": "拖拽盒子",
      "frontmatter": {
        "title": "拖拽盒子",
        "date": "2021-06-07T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "drag"
        ]
      },
      "regularPath": "/components/DragBox.html",
      "relativePath": "components/DragBox.md",
      "key": "v-28ef0e24",
      "path": "/components/DragBox.html",
      "headers": [
        {
          "level": 2,
          "title": "推荐使用vue-draggable",
          "slug": "推荐使用vue-draggable"
        }
      ]
    },
    {
      "title": "优惠券",
      "frontmatter": {
        "title": "优惠券",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "ticket"
        ]
      },
      "regularPath": "/components/ticket.html",
      "relativePath": "components/ticket.md",
      "key": "v-7d378f1e",
      "path": "/components/ticket.html"
    },
    {
      "title": "game",
      "frontmatter": {
        "title": "game",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "ticket"
        ]
      },
      "regularPath": "/game/",
      "relativePath": "game/README.md",
      "key": "v-53a283ed",
      "path": "/game/"
    },
    {
      "title": "About Me",
      "frontmatter": {
        "title": "About Me",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "ticket"
        ]
      },
      "regularPath": "/pages/",
      "relativePath": "pages/README.md",
      "key": "v-b80bdf66",
      "path": "/pages/"
    },
    {
      "title": "快速启动！",
      "frontmatter": {
        "title": "快速启动！",
        "date": "2021-12-05T00:00:00.000Z"
      },
      "regularPath": "/components/home.html",
      "relativePath": "components/home.md",
      "key": "v-79eb2f3e",
      "path": "/components/home.html",
      "headers": [
        {
          "level": 2,
          "title": "如果你想npm安装",
          "slug": "如果你想npm安装"
        },
        {
          "level": 2,
          "title": "如果你想CDN引入",
          "slug": "如果你想cdn引入"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/pages/ticket.html",
      "relativePath": "pages/ticket.md",
      "key": "v-1ae1d77c",
      "path": "/pages/ticket.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "svg Tags"
      },
      "regularPath": "/tag/svg/",
      "key": "v-322cf816",
      "path": "/tag/svg/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "btn Tags"
      },
      "regularPath": "/tag/btn/",
      "key": "v-323c7a06",
      "path": "/tag/btn/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "drag Tags"
      },
      "regularPath": "/tag/drag/",
      "key": "v-151c8dde",
      "path": "/tag/drag/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ticket Tags"
      },
      "regularPath": "/tag/ticket/",
      "key": "v-c1e2ae8e",
      "path": "/tag/ticket/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "components Categories"
      },
      "regularPath": "/categories/components/",
      "key": "v-acfe980a",
      "path": "/categories/components/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "authorAvatar": "/hero.jpg",
    "logo": "/hero.jpg",
    "nav": [
      {
        "text": "About Me",
        "link": "/pages/"
      },
      {
        "text": "组件库",
        "link": "/components/home"
      },
      {
        "text": "游戏",
        "link": "/game/"
      }
    ],
    "sidebar": {
      "/components/": [
        {
          "title": "快速启动！",
          "collapsable": true,
          "path": "home"
        },
        {
          "title": "优惠券",
          "collapsable": true,
          "path": "ticket"
        },
        {
          "title": "奇怪的按钮",
          "collapsable": true,
          "path": "btn"
        },
        {
          "title": "我跟ui有仇之仪表盘",
          "collapsable": true,
          "path": "Dashboard"
        },
        {
          "title": "移动的方块",
          "collapsable": true,
          "path": "DragBox"
        }
      ]
    },
    "blogConfig": {
      "socialLinks": [
        {
          "icon": "reco-blog",
          "link": "https://www.yuque.com/gebixiaojingang"
        },
        {
          "icon": "reco-npm",
          "link": "https://www.npmjs.com/~ytbigking"
        }
      ]
    },
    "friendLink": [
      {
        "title": "语雀",
        "desc": "一些日常以及遇到的坑",
        "logo": "https://gw.alipayobjects.com/mdn/prod_resource/afts/img/A*FsnmRIiTfe0AAAAAAAAAAABkARQnAQ",
        "link": "https://www.yuque.com/gebixiaojingang"
      }
    ]
  }
}