/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Yang Tao",
  "description": "",
  "base": "/bigking/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImage": "/back.jpg",
        "bgImageStyle": {
          "height": "750px"
        },
        "heroText": "Yang Tao",
        "tagline": "前端就是不断重复造轮子的过程",
        "heroTextStyle": {
          "font-size": "26px",
          "color": "#FFF"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-52eef96c",
      "path": "/"
    },
    {
      "title": "svg",
      "frontmatter": {
        "title": "svg",
        "date": "2021-12-13T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "svg"
        ]
      },
      "regularPath": "/components/Dashboard.html",
      "relativePath": "components/Dashboard.md",
      "key": "v-4014f6f4",
      "path": "/components/Dashboard.html"
    },
    {
      "title": "echarts拖拽关系图",
      "frontmatter": {
        "title": "echarts拖拽关系图",
        "date": "2021-12-21T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "echarts"
        ]
      },
      "regularPath": "/components/graph.html",
      "relativePath": "components/graph.md",
      "key": "v-dead3780",
      "path": "/components/graph.html",
      "headers": [
        {
          "level": 2,
          "title": "series-graph.draggable",
          "slug": "series-graph-draggable"
        },
        {
          "level": 3,
          "title": "结果如下",
          "slug": "结果如下"
        },
        {
          "level": 3,
          "title": "为啥节点拖拽之后会弹回去啊？",
          "slug": "为啥节点拖拽之后会弹回去啊"
        },
        {
          "level": 3,
          "title": "经过我苦苦翻阅文档，查阅资料，疯狂百度几小时之后，我",
          "slug": "经过我苦苦翻阅文档-查阅资料-疯狂百度几小时之后-我"
        },
        {
          "level": 2,
          "title": "series-graph.fixed",
          "slug": "series-graph-fixed"
        },
        {
          "level": 2,
          "title": "因为你没给每个节点加上坐标值，加了fixed后，每个节点都要有自己的坐标值才行奥",
          "slug": "因为你没给每个节点加上坐标值-加了fixed后-每个节点都要有自己的坐标值才行奥"
        },
        {
          "level": 3,
          "title": "OKOK，我加 （这边给每个节点加上坐标，就像排位置一样，之后想排成什么样子都可以在这里去给坐标，但是具体的位置就要靠你自己去算了，还是挺有意思的）",
          "slug": "okok-我加-这边给每个节点加上坐标-就像排位置一样-之后想排成什么样子都可以在这里去给坐标-但是具体的位置就要靠你自己去算了-还是挺有意思的"
        },
        {
          "level": 3,
          "title": "加完之后，大功告成",
          "slug": "加完之后-大功告成"
        },
        {
          "level": 2,
          "title": "太年轻，太简单了！事情往往都是一波三折的",
          "slug": "太年轻-太简单了-事情往往都是一波三折的"
        },
        {
          "level": 3,
          "title": "因为你加了fixed，所以所有节点都被固定了，所以不好意思，你的节点这时候是拖不动的，但是去掉fixed，你的节点是不固定的，拖了之后会弹回来，陷入了循环，这时候产生了一种奇怪的现象，我需要fixed，但是我又不需要fixed，我需要draggable，但是我又不需要draggable",
          "slug": "因为你加了fixed-所以所有节点都被固定了-所以不好意思-你的节点这时候是拖不动的-但是去掉fixed-你的节点是不固定的-拖了之后会弹回来-陷入了循环-这时候产生了一种奇怪的现象-我需要fixed-但是我又不需要fixed-我需要draggable-但是我又不需要draggable"
        },
        {
          "level": 3,
          "title": "终于，我想到了，canvas就是一个画布，东西都是画上去的，也就是说我加了fixed和draggable之后，我拖动节点，如果可以获取到节点的坐标，在松开鼠标之后，把节点坐标更新，再重新把整个echarts画一遍不就欧克了？so easy嘛",
          "slug": "终于-我想到了-canvas就是一个画布-东西都是画上去的-也就是说我加了fixed和draggable之后-我拖动节点-如果可以获取到节点的坐标-在松开鼠标之后-把节点坐标更新-再重新把整个echarts画一遍不就欧克了-so-easy嘛"
        },
        {
          "level": 2,
          "title": "好，怎么获取坐标呢？",
          "slug": "好-怎么获取坐标呢"
        },
        {
          "level": 3,
          "title": "这边具体过程忘记了，在on(\"mouseup\")里面的回调里可以获得，但是有坑，网上有些回答的坐标不是正确的坐标，用了之后位置会偏到十万八千里去，甚至你的图会突然消失，因为图被拉得很大很大",
          "slug": "这边具体过程忘记了-在on-mouseup-里面的回调里可以获得-但是有坑-网上有些回答的坐标不是正确的坐标-用了之后位置会偏到十万八千里去-甚至你的图会突然消失-因为图被拉得很大很大"
        },
        {
          "level": 2,
          "title": "坑还是有几个的",
          "slug": "坑还是有几个的"
        }
      ]
    },
    {
      "title": "文字效果",
      "frontmatter": {
        "title": "文字效果",
        "date": "2021-12-24T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "css"
        ]
      },
      "regularPath": "/components/text.html",
      "relativePath": "components/text.md",
      "key": "v-c4c2b404",
      "path": "/components/text.html"
    },
    {
      "title": "一些奇怪的按钮",
      "frontmatter": {
        "title": "一些奇怪的按钮",
        "date": "2021-11-07T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "btn"
        ]
      },
      "regularPath": "/components/btn.html",
      "relativePath": "components/btn.md",
      "key": "v-98e0ed38",
      "path": "/components/btn.html"
    },
    {
      "title": "拖拽盒子",
      "frontmatter": {
        "title": "拖拽盒子",
        "date": "2021-06-07T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "drag"
        ]
      },
      "regularPath": "/components/DragBox.html",
      "relativePath": "components/DragBox.md",
      "key": "v-28ef0e24",
      "path": "/components/DragBox.html",
      "headers": [
        {
          "level": 2,
          "title": "推荐使用vue-draggable",
          "slug": "推荐使用vue-draggable"
        }
      ]
    },
    {
      "title": "clip-path",
      "frontmatter": {
        "title": "clip-path",
        "date": "2021-12-24T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "css"
        ]
      },
      "regularPath": "/components/clip.html",
      "relativePath": "components/clip.md",
      "key": "v-3a78ea44",
      "path": "/components/clip.html",
      "headers": [
        {
          "level": 3,
          "title": "利用clip-path将一块区域裁剪，但是任然占据高度，没有脱离文档流，算是做这种类型的盒子的一种思路吧",
          "slug": "利用clip-path将一块区域裁剪-但是任然占据高度-没有脱离文档流-算是做这种类型的盒子的一种思路吧"
        }
      ]
    },
    {
      "title": "优惠券",
      "frontmatter": {
        "title": "优惠券",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "ticket"
        ]
      },
      "regularPath": "/components/ticket.html",
      "relativePath": "components/ticket.md",
      "key": "v-7d378f1e",
      "path": "/components/ticket.html"
    },
    {
      "title": "快速启动！",
      "frontmatter": {
        "title": "快速启动！",
        "date": "2021-12-05T00:00:00.000Z"
      },
      "regularPath": "/components/home.html",
      "relativePath": "components/home.md",
      "key": "v-79eb2f3e",
      "path": "/components/home.html",
      "headers": [
        {
          "level": 2,
          "title": "如果你想npm安装",
          "slug": "如果你想npm安装"
        },
        {
          "level": 2,
          "title": "如果你想CDN引入",
          "slug": "如果你想cdn引入"
        }
      ]
    },
    {
      "title": "game",
      "frontmatter": {
        "title": "game",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "ticket"
        ]
      },
      "regularPath": "/game/",
      "relativePath": "game/README.md",
      "key": "v-53a283ed",
      "path": "/game/"
    },
    {
      "title": "game",
      "frontmatter": {
        "title": "game",
        "date": "2023-06-16T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "kunkun"
        ]
      },
      "regularPath": "/kunkun/",
      "relativePath": "kunkun/README.md",
      "key": "v-e5ffd4a6",
      "path": "/kunkun/"
    },
    {
      "title": "About Me",
      "frontmatter": {
        "title": "About Me",
        "date": "2021-01-22T00:00:00.000Z",
        "categories": [
          "components"
        ],
        "tags": [
          "ticket"
        ]
      },
      "regularPath": "/pages/",
      "relativePath": "pages/README.md",
      "key": "v-b80bdf66",
      "path": "/pages/"
    },
    {
      "frontmatter": {},
      "regularPath": "/pages/ticket.html",
      "relativePath": "pages/ticket.md",
      "key": "v-1ae1d77c",
      "path": "/pages/ticket.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "svg Tags"
      },
      "regularPath": "/tag/svg/",
      "key": "v-322cf816",
      "path": "/tag/svg/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "echarts Tags"
      },
      "regularPath": "/tag/echarts/",
      "key": "v-119ea9c2",
      "path": "/tag/echarts/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "css Tags"
      },
      "regularPath": "/tag/css/",
      "key": "v-323b9794",
      "path": "/tag/css/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "btn Tags"
      },
      "regularPath": "/tag/btn/",
      "key": "v-323c7a06",
      "path": "/tag/btn/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "drag Tags"
      },
      "regularPath": "/tag/drag/",
      "key": "v-151c8dde",
      "path": "/tag/drag/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ticket Tags"
      },
      "regularPath": "/tag/ticket/",
      "key": "v-c1e2ae8e",
      "path": "/tag/ticket/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "kunkun Tags"
      },
      "regularPath": "/tag/kunkun/",
      "key": "v-4fe80e76",
      "path": "/tag/kunkun/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "components Categories"
      },
      "regularPath": "/categories/components/",
      "key": "v-acfe980a",
      "path": "/categories/components/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "authorAvatar": "/hero.jpg",
    "logo": "/hero.jpg",
    "nav": [
      {
        "text": "组件库",
        "link": "/components/home"
      },
      {
        "text": "游戏",
        "link": "/game/"
      },
      {
        "text": "坤坤工具",
        "link": "/kunkun/"
      }
    ],
    "sidebar": {
      "/components/": [
        {
          "title": "快速启动!",
          "collapsable": true,
          "path": "home"
        },
        {
          "title": "优惠券",
          "collapsable": true,
          "path": "ticket"
        },
        {
          "title": "按钮",
          "collapsable": true,
          "path": "btn"
        },
        {
          "title": "我跟ui有仇之仪表盘",
          "collapsable": true,
          "path": "Dashboard"
        },
        {
          "title": "移动的方块",
          "collapsable": true,
          "path": "DragBox"
        },
        {
          "title": "拖拽echarts关系图!",
          "collapsable": true,
          "path": "graph"
        },
        {
          "title": "利用clip-path实现一些动效",
          "collapsable": true,
          "path": "clip"
        },
        {
          "title": "文字效果合集",
          "collapsable": true,
          "path": "text"
        }
      ]
    },
    "blogConfig": {
      "socialLinks": [
        {
          "icon": "reco-blog",
          "link": "https://www.yuque.com/gebixiaojingang"
        },
        {
          "icon": "reco-npm",
          "link": "https://www.npmjs.com/~ytbigking"
        }
      ]
    },
    "friendLink": [
      {
        "title": "语雀",
        "desc": "一些日常以及遇到的坑",
        "logo": "https://gw.alipayobjects.com/mdn/prod_resource/afts/img/A*FsnmRIiTfe0AAAAAAAAAAABkARQnAQ",
        "link": "https://www.yuque.com/gebixiaojingang"
      }
    ]
  }
}