/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "svg": {
      "key": "svg",
      "scope": "tags",
      "path": "/tag/svg/",
      "pageKeys": [
        "v-4014f6f4"
      ]
    },
    "btn": {
      "key": "btn",
      "scope": "tags",
      "path": "/tag/btn/",
      "pageKeys": [
        "v-98e0ed38"
      ]
    },
    "drag": {
      "key": "drag",
      "scope": "tags",
      "path": "/tag/drag/",
      "pageKeys": [
        "v-28ef0e24"
      ]
    },
    "ticket": {
      "key": "ticket",
      "scope": "tags",
      "path": "/tag/ticket/",
      "pageKeys": [
        "v-7d378f1e",
        "v-53a283ed",
        "v-b80bdf66"
      ]
    }
  },
  "categories": {
    "components": {
      "key": "components",
      "scope": "categories",
      "path": "/categories/components/",
      "pageKeys": [
        "v-4014f6f4",
        "v-98e0ed38",
        "v-28ef0e24",
        "v-7d378f1e",
        "v-53a283ed",
        "v-b80bdf66"
      ]
    }
  },
  "timeline": {}
}