/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "drag": {
      "key": "drag",
      "scope": "tags",
      "path": "/tag/drag/",
      "pageKeys": [
        "v-28ef0e24"
      ]
    },
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-3a78ea44",
        "v-c4c2b404"
      ]
    },
    "echarts": {
      "key": "echarts",
      "scope": "tags",
      "path": "/tag/echarts/",
      "pageKeys": [
        "v-dead3780"
      ]
    },
    "btn": {
      "key": "btn",
      "scope": "tags",
      "path": "/tag/btn/",
      "pageKeys": [
        "v-98e0ed38"
      ]
    },
    "ticket": {
      "key": "ticket",
      "scope": "tags",
      "path": "/tag/ticket/",
      "pageKeys": [
        "v-7d378f1e",
        "v-53a283ed",
        "v-b80bdf66"
      ]
    },
    "kunkun": {
      "key": "kunkun",
      "scope": "tags",
      "path": "/tag/kunkun/",
      "pageKeys": [
        "v-e5ffd4a6"
      ]
    },
    "svg": {
      "key": "svg",
      "scope": "tags",
      "path": "/tag/svg/",
      "pageKeys": [
        "v-4014f6f4"
      ]
    }
  },
  "categories": {
    "components": {
      "key": "components",
      "scope": "categories",
      "path": "/categories/components/",
      "pageKeys": [
        "v-28ef0e24",
        "v-3a78ea44",
        "v-dead3780",
        "v-98e0ed38",
        "v-7d378f1e",
        "v-c4c2b404",
        "v-53a283ed",
        "v-e5ffd4a6",
        "v-b80bdf66",
        "v-4014f6f4"
      ]
    }
  },
  "timeline": {}
}