/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "svg",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/svg/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "btn",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/btn/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "drag",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/drag/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "ticket",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/ticket/","interval":[0,3]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "components",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/components/","interval":[0,6]}],
  prevText: "Prev",
  nextText: "Next",
}]